sudo: required
dist: trusty
language: generic
env:
    - TEST=cxx CXX="g++" NETMAP=no RECVMMSG=yes EVENTFD=yes IBV=no
    - TEST=cxx CXX="g++" NETMAP=yes RECVMMSG=no EVENTFD=no IBV=yes
    - TEST=cxx CXX="clang++" NETMAP=no RECVMMSG=yes EVENTFD=yes IBV=no
    - TEST=cxx CXX="clang++" NETMAP=yes RECVMMSG=no EVENTFD=no IBV=yes
    - TEST=python2 CC="gcc" CXX="g++"
    - TEST=python2 CC="clang" CXX="clang++"
    - TEST=python3 CC="gcc" CXX="g++"
    - TEST=python3 CC="clang" CXX="clang++"
addons:
    apt:
        packages:
            - gcc
            - g++
            - clang
            - libboost-system1.55-dev
            - libboost-python1.55-dev
            - libboost-test1.55-dev
            - libboost-program-options1.55-dev
            - python-dev
            - python3-dev
            - python-pip
            - python3-pip
            - librdmacm-dev
            - libibverbs-dev
install:
    - ./travis-install.sh
script:
    - ./travis-script.sh
