language: python
python:
    - "2.7"
    - "3.4"
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libboost-python-dev
install:
    - pip install -r requirements.txt
    - pip install .
script: nosetests
