language: generic
cache:
    - ccache
    - pip
matrix:
    include:
        - os: linux
          sudo: false
          dist: trusty
          env: TEST=cxx CXX="ccache g++" NETMAP=no RECVMMSG=yes EVENTFD=yes IBV=no
        - os: linux
          sudo: false
          dist: trusty
          env: TEST=cxx CXX="ccache g++" NETMAP=yes RECVMMSG=no EVENTFD=no IBV=yes
        - os: linux
          sudo: false
          dist: trusty
          env: TEST=cxx CXX="ccache clang++-3.5" NETMAP=no RECVMMSG=yes EVENTFD=yes IBV=no
        - os: linux
          sudo: false
          dist: trusty
          env: TEST=cxx CXX="ccache clang++-3.5" NETMAP=yes RECVMMSG=no EVENTFD=no IBV=yes
        - os: linux
          sudo: false
          dist: trusty
          env: TEST=python2 CC="ccache gcc" CXX="g++"
        - os: linux
          sudo: false
          dist: trusty
          env: TEST=python2 CC="ccache clang-3.5" CXX="clang++-3.5"
        - os: linux
          sudo: false
          dist: trusty
          env: TEST=python3 CC="ccache gcc" CXX="g++"
        - os: linux
          sudo: false
          dist: trusty
          env: TEST=python3 CC="ccache clang-3.5" CXX="clang++-3.5"
        - os: osx
          osx_image: xcode7.3
          env: TEST=cxx CXX="clang++" NETMAP=no RECVMMSG=no EVENTFD=no IBV=no
        - os: osx
          osx_image: xcode7.3
          env: TEST=python2 CC="clang" CXX="clang++"
        - os: osx
          osx_image: xcode7.3
          env: TEST=python3 CC="clang" CXX="clang++"
addons:
    apt:
        packages:
            - gcc
            - g++
            - clang-3.5
            - libboost-system1.55-dev
            - libboost-python1.55-dev
            - libboost-test1.55-dev
            - libboost-program-options1.55-dev
            - python-dev
            - python3-dev
            - python-pip
            - python3-pip
            - librdmacm-dev
            - libibverbs-dev
before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" && "$TEST" == "python2" ]]; then brew update; brew install python; brew reinstall boost --with-python; brew install boost-python; pip install virtualenv; virtualenv venv; source venv/bin/activate; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" && "$TEST" == "python3" ]]; then brew update; brew install python3; brew reinstall boost --with-python3; brew install boost-python --with-python3; pyvenv venv; source venv/bin/activate; fi
install:
    - ./travis-install.sh
script:
    - ./travis-script.sh
