language: python
python:
    - "2.7"
    - "3.4"
before_install:
    - sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq
    - sudo apt-get install -qq gcc-4.8 g++-4.8 libboost-python-dev
install:
    - pip install -r requirements.txt
    - CC=gcc-4.8 pip install .
script: nosetests
