language: python
python:
    - "2.7"
    - "3.4"
before_install:
    - sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq
    - sudo apt-get install -qq gcc-4.8 libboost-python-dev
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50
install:
    - pip install -r requirements.txt
    - pip install .
script: nosetests
