sudo: false
language: python
python:
    # Note: can only use the system python versions
    - "2.7"
    - "3.2"
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - boost-latest
        packages:
            - gcc-4.8
            - g++-4.8
            - libboost-system1.55-dev
            - libboost-python1.55-dev
            - python3-dev
install:
    - cat /etc/lsb-release
    - pip install -r requirements.txt
    # PySPEAD tests are optional, so not listed in requirements.txt
    - if [[ "$TRAVIS_PYTHON_VERSION" == 2.* ]]; then pip install git+https://github.com/ska-sa/PySPEAD#egg=spead; fi
    # The -e is necessary to make nosetests work, because otherwise it tries to find the
    # .so in the current directory instead of the install directory.
    - CC=gcc-4.8 pip install -e .
script: nosetests -v
